name: Java Tests

on: [push] # Trigger the workflow on each push to the repository

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest # The operating system for the workflow

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 # This step checks out your code

      - name: Set Up Java
        uses: actions/setup-java@v2 # Set up Java on the runner
        with:
          java-version: '17' # Use the desired Java version

      - name: Build with Maven
        run: mvn clean test # Replace with your build and test commands
